
language: php

php:
  - 7.2
  - 7.3

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
      LARAVEL_VERSION="5.7.*"
    - COMPOSER_FLAGS="--prefer-lowest"
      LARAVEL_VERSION="5.8.*"
    - COMPOSER_FLAGS=""
      LARAVEL_VERSION="5.7.*"
    - COMPOSER_FLAGS=""
      LARAVEL_VERSION="5.8.*"

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist --dev

script:
  - php vendor/bin/phpunit --no-coverage
